global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net;
global using System.Runtime.Serialization;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Hosting;
