jobs:
- job: DacpacBuild
  dependsOn: CodeBuild
  pool:
    name: DAS - Continuous Integration
    demands: Agent.OS -equals Windows_NT
  workspace:
    clean: all
  steps:
  - task: VSBuild@1
    displayName: Build DACPAC
    inputs:
      solution: src/SFA.DAS.EAS.Employer_Account.Database/SFA.DAS.EAS.Employer_Account.Database.sqlproj
      platform: any cpu
      configuration: release
      msbuildArgs: /p:PackageLocation="$(build.artifactstagingdirectory)/publish"

  - task: CopyFiles@2
    displayName: Copy Files to - $(build.artifactstagingdirectory)
    inputs:
      contents: |
        src/**/*.dacpac
      targetFolder: $(build.artifactstagingdirectory)/publish

  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact - ApprenticeCommitmentsApi
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: ApprenticeCommitmentsApiDacpac
