CREATE TABLE [account].[Notification]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserId] BIGINT NOT NULL,
	[DateTime] DATETIME NOT NULL,
	[ForecFormat] BIT NOT NULL DEFAULT(0),
	[TemplateId] VARCHAR(20),
	[Data] NVARCHAR(MAX),
	[MessageFormat] TINYINT  NOT NULL DEFAULT(0)
)
