// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.EmployerFinance.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Late Accounts Feature")]
    public partial class LateAccountsFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Late-accounts.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Late Accounts Feature", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1 - Account is opened on the 23 MAY 2017 and after only added valid PAYE HMRC sub" +
            "missions no older than 12 months old - excludes 1 HMRC submission")]
        public virtual void _1_AccountIsOpenedOnThe23MAY2017AndAfterOnlyAddedValidPAYEHMRCSubmissionsNoOlderThan12MonthsOld_Excludes1HMRCSubmission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1 - Account is opened on the 23 MAY 2017 and after only added valid PAYE HMRC sub" +
                    "missions no older than 12 months old - excludes 1 HMRC submission", null, ((string[])(null)));
#line 3
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 4
 testRunner.Given("An employer is adding a PAYE which has submissions older than the 12 month expiry" +
                    " rule limit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate"});
            table1.AddRow(new string[] {
                        "999000101",
                        "1000",
                        "17-18",
                        "1",
                        "1",
                        "2017-05-19"});
            table1.AddRow(new string[] {
                        "999000102",
                        "2000",
                        "17-18",
                        "2",
                        "1",
                        "2017-06-19"});
            table1.AddRow(new string[] {
                        "999000103",
                        "3000",
                        "17-18",
                        "3",
                        "1",
                        "2017-07-19"});
            table1.AddRow(new string[] {
                        "999000104",
                        "4000",
                        "17-18",
                        "4",
                        "1",
                        "2017-08-19"});
            table1.AddRow(new string[] {
                        "999000105",
                        "5000",
                        "17-18",
                        "5",
                        "1",
                        "2017-09-19"});
            table1.AddRow(new string[] {
                        "999000106",
                        "6000",
                        "17-18",
                        "6",
                        "1",
                        "2017-10-19"});
            table1.AddRow(new string[] {
                        "999000107",
                        "7000",
                        "17-18",
                        "7",
                        "1",
                        "2017-11-19"});
            table1.AddRow(new string[] {
                        "999000108",
                        "8000",
                        "17-18",
                        "8",
                        "1",
                        "2017-12-19"});
            table1.AddRow(new string[] {
                        "999000109",
                        "9000",
                        "17-18",
                        "9",
                        "1",
                        "2018-01-19"});
            table1.AddRow(new string[] {
                        "999000110",
                        "10000",
                        "17-18",
                        "10",
                        "1",
                        "2018-02-19"});
            table1.AddRow(new string[] {
                        "999000111",
                        "11000",
                        "17-18",
                        "11",
                        "1",
                        "2018-03-19"});
            table1.AddRow(new string[] {
                        "999000112",
                        "12000",
                        "17-18",
                        "12",
                        "1",
                        "2018-04-19"});
            table1.AddRow(new string[] {
                        "999000113",
                        "1000",
                        "18-19",
                        "1",
                        "1",
                        "2018-05-19"});
#line 5
 testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table1, "And ");
#line 20
 testRunner.When("we refresh levy data for paye scheme on the 5/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.And("all the transaction lines in this scenario have had their transaction date update" +
                    "d to their created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.Then("we should see a level 1 screen with a levy declared of 1100 on the 5/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
 testRunner.And("we should see a level 1 screen with a balance of 13200 on the 5/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2 - Account is opened on the 22 MAY 2017 and after only added valid submissions n" +
            "o older than 12 months old - excludes 2 HMRC submissions")]
        public virtual void _2_AccountIsOpenedOnThe22MAY2017AndAfterOnlyAddedValidSubmissionsNoOlderThan12MonthsOld_Excludes2HMRCSubmissions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2 - Account is opened on the 22 MAY 2017 and after only added valid submissions n" +
                    "o older than 12 months old - excludes 2 HMRC submissions", null, ((string[])(null)));
#line 25
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 26
 testRunner.Given("An employer is adding a PAYE which has submissions older than the 12 month expiry" +
                    " rule limit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate"});
            table2.AddRow(new string[] {
                        "999000101",
                        "1000",
                        "17-18",
                        "1",
                        "1",
                        "2017-05-19"});
            table2.AddRow(new string[] {
                        "999000102",
                        "2000",
                        "17-18",
                        "2",
                        "1",
                        "2017-06-19"});
            table2.AddRow(new string[] {
                        "999000107",
                        "7000",
                        "17-18",
                        "7",
                        "1",
                        "2017-11-19"});
            table2.AddRow(new string[] {
                        "999000108",
                        "8000",
                        "17-18",
                        "8",
                        "1",
                        "2017-12-19"});
            table2.AddRow(new string[] {
                        "999000109",
                        "9000",
                        "17-18",
                        "9",
                        "1",
                        "2018-01-19"});
            table2.AddRow(new string[] {
                        "999000110",
                        "10000",
                        "17-18",
                        "10",
                        "1",
                        "2018-02-19"});
            table2.AddRow(new string[] {
                        "999000111",
                        "11000",
                        "17-18",
                        "11",
                        "1",
                        "2018-03-19"});
            table2.AddRow(new string[] {
                        "999000112",
                        "12000",
                        "17-18",
                        "12",
                        "1",
                        "2018-04-19"});
            table2.AddRow(new string[] {
                        "999000113",
                        "1000",
                        "18-19",
                        "1",
                        "1",
                        "2018-05-19"});
#line 27
 testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table2, "And ");
#line 38
 testRunner.When("we refresh levy data for paye scheme on the 5/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.And("all the transaction lines in this scenario have had their transaction date update" +
                    "d to their created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.Then("we should see a level 1 screen with a levy declared of 1100 on the 5/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 41
 testRunner.And("we should see a level 1 screen with a balance of 13200 on the 5/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3 - Account is opened on the 22 MAY 2017 and after only added valid submissions n" +
            "o older than 12 months old - no HMRC submissions older than 12 months")]
        public virtual void _3_AccountIsOpenedOnThe22MAY2017AndAfterOnlyAddedValidSubmissionsNoOlderThan12MonthsOld_NoHMRCSubmissionsOlderThan12Months()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3 - Account is opened on the 22 MAY 2017 and after only added valid submissions n" +
                    "o older than 12 months old - no HMRC submissions older than 12 months", null, ((string[])(null)));
#line 44
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 45
 testRunner.Given("An employer is adding a PAYE which has submissions older than the 12 month expiry" +
                    " rule limit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate"});
            table3.AddRow(new string[] {
                        "999000101",
                        "0",
                        "17-18",
                        "1",
                        "1",
                        "2017-05-19"});
            table3.AddRow(new string[] {
                        "999000102",
                        "0",
                        "17-18",
                        "2",
                        "1",
                        "2017-06-19"});
            table3.AddRow(new string[] {
                        "999000103",
                        "0",
                        "17-18",
                        "3",
                        "1",
                        "2017-07-19"});
            table3.AddRow(new string[] {
                        "999000104",
                        "0",
                        "17-18",
                        "4",
                        "1",
                        "2017-08-19"});
            table3.AddRow(new string[] {
                        "999000105",
                        "0",
                        "17-18",
                        "5",
                        "1",
                        "2017-09-19"});
            table3.AddRow(new string[] {
                        "999000106",
                        "0",
                        "17-18",
                        "6",
                        "1",
                        "2017-10-19"});
            table3.AddRow(new string[] {
                        "999000107",
                        "7000",
                        "17-18",
                        "7",
                        "1",
                        "2017-11-19"});
            table3.AddRow(new string[] {
                        "999000108",
                        "8000",
                        "17-18",
                        "8",
                        "1",
                        "2017-12-19"});
            table3.AddRow(new string[] {
                        "999000109",
                        "9000",
                        "17-18",
                        "9",
                        "1",
                        "2018-01-19"});
            table3.AddRow(new string[] {
                        "999000110",
                        "10000",
                        "17-18",
                        "10",
                        "1",
                        "2018-02-19"});
            table3.AddRow(new string[] {
                        "999000111",
                        "11000",
                        "17-18",
                        "11",
                        "1",
                        "2018-03-19"});
            table3.AddRow(new string[] {
                        "999000112",
                        "12000",
                        "17-18",
                        "12",
                        "1",
                        "2018-04-19"});
            table3.AddRow(new string[] {
                        "999000113",
                        "1000",
                        "18-19",
                        "1",
                        "1",
                        "2018-05-19"});
#line 46
 testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table3, "And ");
#line 61
 testRunner.When("we refresh levy data for paye scheme on the 5/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.And("all the transaction lines in this scenario have had their transaction date update" +
                    "d to their created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.Then("we should see a level 1 screen with a levy declared of 1100 on the 5/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 64
 testRunner.And("we should see a level 1 screen with a balance of 14300 on the 5/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("4 - An End-of-year-adjustment is for a period older than 12 months and one younge" +
            "r than 12 months is in submissions of a newly added PAYE scheme - excludes 1 HMR" +
            "C submission")]
        public virtual void _4_AnEnd_Of_Year_AdjustmentIsForAPeriodOlderThan12MonthsAndOneYoungerThan12MonthsIsInSubmissionsOfANewlyAddedPAYEScheme_Excludes1HMRCSubmission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4 - An End-of-year-adjustment is for a period older than 12 months and one younge" +
                    "r than 12 months is in submissions of a newly added PAYE scheme - excludes 1 HMR" +
                    "C submission", null, ((string[])(null)));
#line 66
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 67
 testRunner.Given("An employer is adding a PAYE which has submissions older than the 12 month expiry" +
                    " rule limit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate",
                        "EndofYear Adjustment"});
            table4.AddRow(new string[] {
                        "999000101",
                        "1000",
                        "17-18",
                        "1",
                        "1",
                        "2017-05-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000102",
                        "2000",
                        "17-18",
                        "2",
                        "1",
                        "2017-06-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000103",
                        "3000",
                        "17-18",
                        "3",
                        "1",
                        "2017-07-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000104",
                        "4000",
                        "17-18",
                        "4",
                        "1",
                        "2017-08-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000105",
                        "5000",
                        "17-18",
                        "5",
                        "1",
                        "2017-09-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000106",
                        "6000",
                        "17-18",
                        "6",
                        "1",
                        "2017-10-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000107",
                        "7000",
                        "17-18",
                        "7",
                        "1",
                        "2017-11-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000108",
                        "8000",
                        "17-18",
                        "8",
                        "1",
                        "2017-12-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000109",
                        "9000",
                        "17-18",
                        "9",
                        "1",
                        "2018-01-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000110",
                        "10000",
                        "17-18",
                        "10",
                        "1",
                        "2018-02-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000111",
                        "11000",
                        "17-18",
                        "11",
                        "1",
                        "2018-03-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000112",
                        "12000",
                        "17-18",
                        "12",
                        "1",
                        "2018-04-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000113",
                        "1000",
                        "18-19",
                        "1",
                        "1",
                        "2018-05-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000114",
                        "2000",
                        "18-19",
                        "2",
                        "1",
                        "2018-06-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000115",
                        "3000",
                        "18-19",
                        "3",
                        "1",
                        "2018-07-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000116",
                        "4000",
                        "18-19",
                        "4",
                        "1",
                        "2018-08-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000117",
                        "5000",
                        "18-19",
                        "5",
                        "1",
                        "2018-09-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000118",
                        "6000",
                        "18-19",
                        "6",
                        "1",
                        "2018-10-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000119",
                        "11000",
                        "17-18",
                        "12",
                        "1",
                        "2018-10-19",
                        "1"});
            table4.AddRow(new string[] {
                        "999000120",
                        "7000",
                        "18-19",
                        "7",
                        "1",
                        "2018-11-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000121",
                        "8000",
                        "18-19",
                        "8",
                        "1",
                        "2018-12-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000122",
                        "9000",
                        "18-19",
                        "9",
                        "1",
                        "2019-01-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000123",
                        "10000",
                        "18-19",
                        "10",
                        "1",
                        "2019-02-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000124",
                        "11000",
                        "18-19",
                        "11",
                        "1",
                        "2019-03-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000125",
                        "12000",
                        "18-19",
                        "12",
                        "1",
                        "2019-04-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000126",
                        "1000",
                        "19-20",
                        "1",
                        "1",
                        "2019-05-19",
                        "0"});
            table4.AddRow(new string[] {
                        "999000127",
                        "11500",
                        "18-19",
                        "12",
                        "1",
                        "2019-05-19",
                        "1"});
#line 68
 testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table4, "And ");
#line 97
 testRunner.When("we refresh levy data for paye scheme on the 5/2019", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 98
 testRunner.And("all the transaction lines in this scenario have had their transaction date update" +
                    "d to their created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
 testRunner.Then("we should see a level 1 screen with a levy declared of 550 on the 05/2019", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 100
 testRunner.And("we should see a level 1 screen with a balance of 12650 on the 05/2019", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("5 - A PAYE being used to create a new account has been in a different account wit" +
            "hin the 12 month limit - excludes 4 HMRC submissions from a previous account")]
        public virtual void _5_APAYEBeingUsedToCreateANewAccountHasBeenInADifferentAccountWithinThe12MonthLimit_Excludes4HMRCSubmissionsFromAPreviousAccount()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5 - A PAYE being used to create a new account has been in a different account wit" +
                    "hin the 12 month limit - excludes 4 HMRC submissions from a previous account", null, ((string[])(null)));
#line 103
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 104
 testRunner.Given("An employer is adding a PAYE which has submissions older than the 12 month expiry" +
                    " rule limit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate",
                        "EndofYear Adjustment"});
            table5.AddRow(new string[] {
                        "999000108",
                        "8000",
                        "17-18",
                        "8",
                        "1",
                        "2017-12-19",
                        "0"});
            table5.AddRow(new string[] {
                        "999000109",
                        "9000",
                        "17-18",
                        "9",
                        "1",
                        "2018-01-19",
                        "0"});
            table5.AddRow(new string[] {
                        "999000110",
                        "10000",
                        "17-18",
                        "10",
                        "1",
                        "2018-02-19",
                        "0"});
            table5.AddRow(new string[] {
                        "999000111",
                        "11000",
                        "17-18",
                        "11",
                        "1",
                        "2018-03-19",
                        "0"});
#line 105
 testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table5, "And ");
#line 111
 testRunner.And("we refresh levy data for paye scheme on the 03/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 112
 testRunner.And("Another account is opened and associated with the paye scheme", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate",
                        "EndofYear Adjustment"});
            table6.AddRow(new string[] {
                        "999000112",
                        "12000",
                        "17-18",
                        "12",
                        "1",
                        "2018-04-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000113",
                        "1000",
                        "18-19",
                        "1",
                        "1",
                        "2018-05-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000114",
                        "2000",
                        "18-19",
                        "2",
                        "1",
                        "2018-06-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000115",
                        "3000",
                        "18-19",
                        "3",
                        "1",
                        "2018-07-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000116",
                        "4000",
                        "18-19",
                        "4",
                        "1",
                        "2018-08-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000117",
                        "5000",
                        "18-19",
                        "5",
                        "1",
                        "2018-09-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000118",
                        "6000",
                        "18-19",
                        "6",
                        "1",
                        "2018-10-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000119",
                        "12500",
                        "17-18",
                        "12",
                        "1",
                        "2018-10-19",
                        "1"});
            table6.AddRow(new string[] {
                        "999000120",
                        "7000",
                        "18-19",
                        "7",
                        "1",
                        "2018-11-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000121",
                        "8000",
                        "18-19",
                        "8",
                        "1",
                        "2018-12-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000122",
                        "9000",
                        "18-19",
                        "9",
                        "1",
                        "2019-01-19",
                        "0"});
            table6.AddRow(new string[] {
                        "999000123",
                        "10000",
                        "18-19",
                        "10",
                        "1",
                        "2019-02-19",
                        "0"});
#line 113
 testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table6, "And ");
#line 127
 testRunner.When("we refresh levy data for paye scheme on the 02/2019", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 128
 testRunner.And("all the transaction lines in this scenario have had their transaction date update" +
                    "d to their created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 129
 testRunner.Then("we should see a level 1 screen with a levy declared of 1100 on the 02/2019", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 130
 testRunner.And("we should see a level 1 screen with a balance of 12650 on the 02/2019", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("6 - A PAYE being used to create a new account has been in a different account lon" +
            "ger ago than the 12 month limit and the new account includes end of year adjustm" +
            "ents within that time limit and ignores one outside the limit -")]
        public virtual void _6_APAYEBeingUsedToCreateANewAccountHasBeenInADifferentAccountLongerAgoThanThe12MonthLimitAndTheNewAccountIncludesEndOfYearAdjustmentsWithinThatTimeLimitAndIgnoresOneOutsideTheLimit_()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("6 - A PAYE being used to create a new account has been in a different account lon" +
                    "ger ago than the 12 month limit and the new account includes end of year adjustm" +
                    "ents within that time limit and ignores one outside the limit -", "\t\texcludes 13 HMRC submissions including an end of year adjustment relating to a " +
                    "period older than 12 months. ", ((string[])(null)));
#line 132
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 134
 testRunner.Given("An employer is adding a PAYE which has submissions older than the 12 month expiry" +
                    " rule limit", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate",
                        "EndofYear Adjustment"});
            table7.AddRow(new string[] {
                        "999000100",
                        "12000",
                        "16-17",
                        "12",
                        "1",
                        "2017-04-19",
                        "0"});
            table7.AddRow(new string[] {
                        "999000101",
                        "1000",
                        "17-18",
                        "1",
                        "1",
                        "2017-05-19",
                        "0"});
            table7.AddRow(new string[] {
                        "999000102",
                        "2000",
                        "17-18",
                        "2",
                        "1",
                        "2017-06-19",
                        "0"});
            table7.AddRow(new string[] {
                        "999000103",
                        "3000",
                        "17-18",
                        "3",
                        "1",
                        "2017-07-19",
                        "0"});
            table7.AddRow(new string[] {
                        "999000104",
                        "4000",
                        "17-18",
                        "4",
                        "1",
                        "2017-08-19",
                        "0"});
            table7.AddRow(new string[] {
                        "999000105",
                        "5000",
                        "17-18",
                        "5",
                        "1",
                        "2017-09-19",
                        "0"});
#line 135
 testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table7, "And ");
#line 143
 testRunner.And("we refresh levy data for paye scheme on the 09/2017", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
    testRunner.And("Another account is opened and associated with the paye scheme", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate",
                        "EndofYear Adjustment"});
            table8.AddRow(new string[] {
                        "999000106",
                        "6000",
                        "17-18",
                        "6",
                        "1",
                        "2017-10-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000107",
                        "7000",
                        "17-18",
                        "7",
                        "1",
                        "2017-11-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000108",
                        "8000",
                        "17-18",
                        "8",
                        "1",
                        "2017-12-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000109",
                        "9000",
                        "17-18",
                        "9",
                        "1",
                        "2018-01-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000110",
                        "10000",
                        "17-18",
                        "10",
                        "1",
                        "2018-02-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000111",
                        "11000",
                        "17-18",
                        "11",
                        "1",
                        "2018-03-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000112",
                        "12000",
                        "17-18",
                        "12",
                        "1",
                        "2018-04-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000113",
                        "1000",
                        "18-19",
                        "1",
                        "1",
                        "2018-05-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000114",
                        "2000",
                        "18-19",
                        "2",
                        "1",
                        "2018-06-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000115",
                        "3000",
                        "18-19",
                        "3",
                        "1",
                        "2018-07-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000116",
                        "4000",
                        "18-19",
                        "4",
                        "1",
                        "2018-08-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000117",
                        "5000",
                        "18-19",
                        "5",
                        "1",
                        "2018-09-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000118",
                        "6000",
                        "18-19",
                        "6",
                        "1",
                        "2018-10-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000119",
                        "12500",
                        "17-18",
                        "12",
                        "1",
                        "2018-10-19",
                        "1"});
            table8.AddRow(new string[] {
                        "999000120",
                        "7000",
                        "18-19",
                        "7",
                        "1",
                        "2018-11-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000121",
                        "8000",
                        "18-19",
                        "8",
                        "1",
                        "2018-12-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000122",
                        "9000",
                        "18-19",
                        "9",
                        "1",
                        "2019-01-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000123",
                        "10000",
                        "18-19",
                        "10",
                        "1",
                        "2019-02-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000124",
                        "11000",
                        "18-19",
                        "11",
                        "1",
                        "2019-03-19",
                        "0"});
            table8.AddRow(new string[] {
                        "999000125",
                        "13000",
                        "16-17",
                        "12",
                        "1",
                        "2019-03-19",
                        "1"});
#line 145
    testRunner.And("Hmrc return the following submissions for paye scheme", ((string)(null)), table8, "And ");
#line 167
 testRunner.When("we refresh levy data for paye scheme on the 03/2019", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 168
    testRunner.And("all the transaction lines in this scenario have had their transaction date update" +
                    "d to their created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 169
 testRunner.Then("we should see a level 1 screen with a levy declared of 1100 on the 03/2019", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 170
 testRunner.And("we should see a level 1 screen with a balance of 13750 on the 03/2019", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

