// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.EmployerFinance.AcceptanceTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("HMRC-Scenario-02-Seasonal-variations-single-PAYE")]
    public partial class HMRC_Scenario_02_Seasonal_Variations_Single_PAYEFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Scenario-02-Seasonal-variations-single-PAYE.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HMRC-Scenario-02-Seasonal-variations-single-PAYE", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Month-03-submission")]
        public virtual void Month_03_Submission()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Month-03-submission", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("We have an account with id 25", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate"});
            table1.AddRow(new string[] {
                        "999000201",
                        "10000",
                        "17-18",
                        "1",
                        "1",
                        "2017-05-15"});
            table1.AddRow(new string[] {
                        "999000202",
                        "20000",
                        "17-18",
                        "2",
                        "1",
                        "2017-06-15"});
            table1.AddRow(new string[] {
                        "999000203",
                        "18750",
                        "17-18",
                        "3",
                        "1",
                        "2017-07-15"});
#line 5
 testRunner.And("Hmrc return the following submissions for paye scheme 123/ABC", ((string)(null)), table1, "And ");
#line 10
 testRunner.When("we refresh levy data for account id 25 paye scheme 123/ABC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.And("All the transaction lines in this scenario have had there transaction date update" +
                    "d to their created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.Then("account with id 25 should see a level 1 screen with a balance of 20625 on the 07/" +
                    "2017", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 13
 testRunner.And("account with id 25 should see a level 1 screen with a total levy of -1375 on the " +
                    "07/2017", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("account with id 25 should see a level 2 screen with a levy declared of -1250 on t" +
                    "he 07/2017", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("account with id 25 should see a level 2 screen with a top up of -125 on the 07/20" +
                    "17", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Month-12-submission-Checking-2nd-negative-declaration")]
        public virtual void Month_12_Submission_Checking_2Nd_Negative_Declaration()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Month-12-submission-Checking-2nd-negative-declaration", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("We have an account with id 25", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "LevyDueYtd",
                        "Payroll_Year",
                        "Payroll_Month",
                        "English_Fraction",
                        "SubmissionDate"});
            table2.AddRow(new string[] {
                        "999000204",
                        "10000",
                        "17-18",
                        "1",
                        "1",
                        "2017-05-15"});
            table2.AddRow(new string[] {
                        "999000205",
                        "20000",
                        "17-18",
                        "2",
                        "1",
                        "2017-06-15"});
            table2.AddRow(new string[] {
                        "999000206",
                        "18750",
                        "17-18",
                        "3",
                        "1",
                        "2017-07-15"});
            table2.AddRow(new string[] {
                        "999000207",
                        "28750",
                        "17-18",
                        "4",
                        "1",
                        "2017-08-15"});
            table2.AddRow(new string[] {
                        "999000208",
                        "38750",
                        "17-18",
                        "5",
                        "1",
                        "2017-09-15"});
            table2.AddRow(new string[] {
                        "999000209",
                        "48750",
                        "17-18",
                        "6",
                        "1",
                        "2017-10-15"});
            table2.AddRow(new string[] {
                        "999000210",
                        "58750",
                        "17-18",
                        "7",
                        "1",
                        "2017-11-15"});
            table2.AddRow(new string[] {
                        "999000211",
                        "68750",
                        "17-18",
                        "8",
                        "1",
                        "2017-12-15"});
            table2.AddRow(new string[] {
                        "999000212",
                        "67500",
                        "17-18",
                        "9",
                        "1",
                        "2018-01-15"});
            table2.AddRow(new string[] {
                        "999000213",
                        "77500",
                        "17-18",
                        "10",
                        "1",
                        "2018-02-15"});
            table2.AddRow(new string[] {
                        "999000214",
                        "87500",
                        "17-18",
                        "11",
                        "1",
                        "2018-03-15"});
            table2.AddRow(new string[] {
                        "999000215",
                        "97500",
                        "17-18",
                        "12",
                        "1",
                        "2018-04-15"});
#line 19
 testRunner.And("Hmrc return the following submissions for paye scheme 123/ABC", ((string)(null)), table2, "And ");
#line 33
 testRunner.When("we refresh levy data for account id 25 paye scheme 123/ABC", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
 testRunner.And("All the transaction lines in this scenario have had there transaction date update" +
                    "d to their created date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.Then("account with id 25 should see a level 1 screen with a balance of 107250 on the 04" +
                    "/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
 testRunner.And("account with id 25 should see a level 1 screen with a total levy of -1375 on the " +
                    "01/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And("account with id 25 should see a level 2 screen with a levy declared of -1250 on t" +
                    "he 01/2018", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("account with id 25 should see a level 2 screen with a top up of -125 on the 01/20" +
                    "18", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
